// POST /api/usage
//
// The Mac app calls this once per completed transcription to (1) tell us
// the audio was spoken and (2) debit the org's credit ledger. It's the only
// server round-trip the Mac app makes during a normal dictation cycle — the
// transcript itself goes Mac → Deepgram → Mac, never touching us, which is
// the privacy guarantee on the landing page.
//
// Auth: Authorization: Bearer <mac-session-token> for the Mac app, or
// Auth.js session cookie for web callers (testing). Both routes converge
// on the same AuthedUser via requireUserFromRequest — see src/lib/authz.ts.
//
// Body (JSON):
//   {
//     transcriptionClientId: string,  // UUID generated by the Mac app
//     wordCount: number,               // final transcript word count
//     audioMs?: number,                // duration in milliseconds
//     model: string                    // "nova-3", "nova-2", etc.
//   }
//
// Response:
//   200 { ok: true, newBalanceMillicents, autoTopupTriggered }
//   200 { ok: true, duplicate: true }    ← idempotent retry
//   402 { error: "insufficient_credit" } ← no-op, caller should refuse
//   4xx { error: string }                ← bad request / unauth
//
// The endpoint is safe to retry. Deduplication is by (org_id, transcription_
// client_id) on usage_events.

import { z } from "zod";
import { AuthzError, requireUserFromRequest } from "@/lib/authz";
import { getCurrentOrgForUser } from "@/lib/orgs";
import { debitForUsage } from "@/lib/credits";

const bodySchema = z.object({
  transcriptionClientId: z.string().min(8).max(64),
  wordCount: z.number().int().min(0).max(100_000),
  audioMs: z.number().int().min(0).max(60 * 60 * 1000).optional(),
  model: z.string().min(1).max(64),
});

export async function POST(req: Request): Promise<Response> {
  let user;
  try {
    user = await requireUserFromRequest(req);
  } catch (err) {
    const status = err instanceof AuthzError ? err.status : 401;
    return Response.json({ error: "unauthorized" }, { status });
  }

  const json = await req.json().catch(() => null);
  const parsed = bodySchema.safeParse(json);
  if (!parsed.success) {
    return Response.json(
      { error: "bad_body", issues: parsed.error.flatten().fieldErrors },
      { status: 400 }
    );
  }

  const org = await getCurrentOrgForUser(user.id);
  if (!org) {
    return Response.json({ error: "no_org" }, { status: 400 });
  }

  const result = await debitForUsage({
    orgId: org.id,
    userId: user.id,
    transcriptionClientId: parsed.data.transcriptionClientId,
    wordCount: parsed.data.wordCount,
    audioMs: parsed.data.audioMs,
    model: parsed.data.model,
  });

  switch (result.kind) {
    case "ok":
      return Response.json({
        ok: true,
        newBalanceMillicents: result.newBalanceMillicents,
        autoTopupTriggered: result.autoTopupTriggered,
        usageEventId: result.usageEventId,
      });
    case "duplicate":
      return Response.json({
        ok: true,
        duplicate: true,
        usageEventId: result.usageEventId,
      });
    case "insufficient":
      return Response.json(
        { error: "insufficient_credit", balanceMillicents: result.balanceMillicents },
        { status: 402 }
      );
  }
}
