// Privacy Policy. Static content; no D1 reads.
//
// IMPORTANT: this content was drafted from a standard template and
// reflects Speakist's actual data practices as of the last-updated date
// below. It is NOT a substitute for review by counsel before public
// launch. If you change the data flows (e.g. add new third-party
// processors, retention timelines, or analytics), update this document.

import { Nav } from "@/components/marketing/nav";
import { Footer } from "@/components/marketing/footer";

export const metadata = { title: "Privacy Policy — Speakist" };

const LAST_UPDATED = "April 27, 2026";

export default function PrivacyPage() {
  return (
    <div className="flex min-h-screen flex-col">
      <Nav />
      <main className="flex-1">
        <article className="container max-w-3xl py-16 sm:py-24">
          <header className="mb-12 border-b border-border/60 pb-8">
            <p className="text-sm uppercase tracking-[0.2em] text-peach-deep font-medium">
              Privacy
            </p>
            <h1 className="mt-3 text-4xl sm:text-5xl font-semibold tracking-tight">
              Privacy Policy
            </h1>
            <p className="mt-4 text-sm text-muted-foreground">
              Last updated: {LAST_UPDATED}
            </p>
          </header>

          <div className="space-y-10 text-base leading-relaxed text-foreground/90">
            <Section>
              <P>
                Speakist is a dictation product made by Brevoort Studio LLC
                (&ldquo;we,&rdquo; &ldquo;us,&rdquo; &ldquo;our&rdquo;). This
                policy explains what we collect, what we don&apos;t, and how
                we handle the information you share with us.
              </P>
              <P>
                We take a conservative approach to privacy. We collect only
                what we need to run the service, never sell or rent your
                data, and don&apos;t use your content to train AI models.
              </P>
              <P>If you&apos;ve read enough, here&apos;s the short version:</P>
              <UL>
                <LI>We don&apos;t store your audio or transcripts.</LI>
                <LI>
                  We don&apos;t share your personal information with anyone
                  except the infrastructure providers we need to operate.
                </LI>
                <LI>We don&apos;t sell, rent, or trade your data.</LI>
                <LI>
                  We retain only the minimum metadata required for billing
                  and operations.
                </LI>
              </UL>
            </Section>

            <Section title="Information we collect">
              <P>
                <strong>Account information.</strong> When you create an
                account, we collect your email address. You can optionally
                provide a display name. We use a magic-link sign-in flow,
                so we don&apos;t store passwords.
              </P>
              <P>
                <strong>Usage metadata.</strong> Each time you complete a
                transcription, we record:
              </P>
              <UL>
                <LI>A unique transcription ID generated by your device</LI>
                <LI>Word count of the resulting transcript</LI>
                <LI>Audio duration in milliseconds</LI>
                <LI>The transcription model used (e.g., Whisper)</LI>
                <LI>Whether the polish step ran</LI>
                <LI>Cost in fractional cents</LI>
                <LI>Timestamp</LI>
              </UL>
              <P>
                We do <strong>not</strong> store the transcript text or
                audio.
              </P>
              <P>
                <strong>Custom vocabulary.</strong> If you add custom terms
                to your personal vocabulary (e.g., proper nouns, technical
                jargon), we store those terms so they sync across your
                devices.
              </P>
              <P>
                <strong>Billing information.</strong> We track your credit
                balance, top-up history, and Stripe customer ID. Stripe
                processes all payments — we never see your full card
                number or banking details.
              </P>
              <P>
                <strong>Authentication tokens.</strong> When you sign in
                from a device, we store a SHA-256 hash of your refresh
                token. We never store the plaintext token.
              </P>
              <P>
                <strong>Server logs.</strong> Our infrastructure logs
                standard request information (IP address, user agent,
                timestamp, response status) for a limited period for abuse
                prevention and debugging. These logs do not include the
                contents of your transcriptions.
              </P>
            </Section>

            <Section title="What we don&rsquo;t store">
              <P>
                <strong>Audio.</strong> Your dictation audio is sent to our
                backend and forwarded to our transcription provider. The
                audio is held only for the duration of the request —
                typically under a second — and then discarded. It never
                persists in our database, logs, or any other storage
                system we control.
              </P>
              <P>
                <strong>Transcript text.</strong> The transcribed and
                polished text returned to your device is not stored on our
                servers. It exists only in transit between you, our
                transcription provider, and your device. Your final text
                lives wherever you paste it — your email, your notes,
                your messages.
              </P>
              <P>
                <strong>Card numbers.</strong> Payment data is handled
                entirely by Stripe under their PCI-compliant systems. We
                see only metadata Stripe shares (last four digits, customer
                ID, invoice information).
              </P>
            </Section>

            <Section title="When you report a bad transcription">
              <P>
                The Speakist apps include a &ldquo;Report bad
                transcription&rdquo; option in your History view. This is
                the <strong>only</strong> path that uploads any of your
                dictation data to our servers for storage. It runs only
                when you explicitly tap or click Report — there is no
                background submission, no telemetry that mirrors a
                transcription without your action.
              </P>
              <P>When you report a transcription, with your permission we receive:</P>
              <UL>
                <LI>
                  The audio recording (you can uncheck this in the report
                  dialog to send a text-only report)
                </LI>
                <LI>The raw text our transcription model produced</LI>
                <LI>The polished text we delivered to your device</LI>
                <LI>
                  Your correction — what you said the transcript should
                  have been
                </LI>
                <LI>
                  Any optional note or category you chose (&ldquo;wrong
                  word&rdquo;, &ldquo;punctuation&rdquo;, etc.)
                </LI>
              </UL>
              <P>
                We use this data exclusively to improve transcription
                accuracy — specifically, to grow our regression test
                suite and to tune the prompts used by our polish model.
                We retain it indefinitely so that a fix for your reported
                issue today can keep working a year from now without
                regressing.
              </P>
              <P>
                <strong>Workspace opt-out.</strong> Your workspace owner
                can turn off the Report feature for everyone in the
                workspace. When disabled, the Report button is hidden
                from the apps and the server refuses any submission. Ask
                your owner if you&rsquo;d like to discuss enabling or
                disabling it for your team.
              </P>
            </Section>

            <Section title="How we use the information">
              <P>We use the information we collect to:</P>
              <UL>
                <LI>Authenticate you and your devices</LI>
                <LI>Operate, maintain, and improve the service</LI>
                <LI>Calculate your usage and bill you accurately</LI>
                <LI>
                  Send transactional emails (e.g., sign-in links, billing
                  receipts)
                </LI>
                <LI>Detect abuse and protect the service</LI>
                <LI>
                  Aggregate usage data to understand product performance
                  (no individual identification)
                </LI>
              </UL>
            </Section>

            <Section title="What we don&rsquo;t do">
              <P>We do not:</P>
              <UL>
                <LI>
                  Sell, rent, or trade your personal information to anyone,
                  ever
                </LI>
                <LI>
                  Share your data with advertisers or marketing networks
                </LI>
                <LI>
                  Use tracking pixels or third-party advertising cookies
                </LI>
                <LI>Use your audio or transcripts to train AI models</LI>
                <LI>
                  Read transcriptions you didn&rsquo;t explicitly report.
                  We don&rsquo;t store them in the first place.
                </LI>
              </UL>
            </Section>

            <Section title="Third-party services">
              <P>
                To operate Speakist we share limited data with the following
                providers, each of whom has their own privacy commitments:
              </P>
              <UL>
                <LI>
                  <strong>Cloudflare</strong> — hosting, edge compute, and
                  database. Speakist data is stored on Cloudflare
                  infrastructure. They process the data on our behalf as a
                  sub-processor.
                </LI>
                <LI>
                  <strong>Stripe</strong> — payments. Stripe receives your
                  payment information directly when you make a purchase.
                  We share only your email and metadata identifying which
                  org is charged.
                </LI>
                <LI>
                  <strong>Groq</strong> — transcription and polish. Groq
                  receives your audio for transcription and the resulting
                  text for the polish step. Per Groq&apos;s privacy policy,
                  inputs are not retained after processing.
                </LI>
                <LI>
                  <strong>Deepgram</strong> — alternate transcription
                  provider, used only when a super admin routes an org to
                  Deepgram via its allowed-models list. When used, audio
                  is sent to Deepgram for transcription and not retained
                  after processing.
                </LI>
                <LI>
                  <strong>Resend</strong> — transactional email. We send
                  sign-in links and billing notifications through Resend.
                  They receive your email address and the message we send
                  to you.
                </LI>
              </UL>
              <P>
                Each provider may store request metadata under their own
                retention policies. We pass through only what is required
                to provide the service.
              </P>
            </Section>

            <Section title="Data retention">
              <UL>
                <LI>
                  Account information is retained while your account is
                  active.
                </LI>
                <LI>
                  Usage events are retained for billing reconciliation. We
                  may purge or aggregate older records over time.
                </LI>
                <LI>
                  Audio and transcripts are not retained — they exist only
                  for the duration of each request.
                </LI>
                <LI>
                  If you delete your account, we delete your account
                  information, billing records, and vocabulary, except
                  where retention is required by law (e.g., tax records).
                </LI>
              </UL>
            </Section>

            <Section title="Your rights">
              <P>You can:</P>
              <UL>
                <LI>
                  <strong>Access</strong> your information at any time via
                  your dashboard
                </LI>
                <LI>
                  <strong>Update</strong> your account information from
                  your settings
                </LI>
                <LI>
                  <strong>Delete</strong> your account by contacting us at
                  hello@brevoortstudio.com or via your settings
                </LI>
                <LI>
                  <strong>Export</strong> your usage and vocabulary data on
                  request
                </LI>
                <LI>
                  <strong>Opt out</strong> of non-transactional emails
                </LI>
              </UL>
              <P>
                If you are in the European Economic Area, the United
                Kingdom, or California, you have additional rights under
                GDPR, UK GDPR, and the CCPA respectively. To exercise those
                rights, email us.
              </P>
            </Section>

            <Section title="Security">
              <P>
                We use industry-standard practices to protect your
                information:
              </P>
              <UL>
                <LI>TLS 1.2+ for all data in transit</LI>
                <LI>
                  Encrypted-at-rest storage where supported by our providers
                </LI>
                <LI>Hashing of authentication tokens</LI>
                <LI>
                  Limited access to systems by team members on a
                  need-to-know basis
                </LI>
              </UL>
              <P>
                No system is perfectly secure. If we ever detect a breach
                affecting your data, we will notify you in line with
                applicable law.
              </P>
            </Section>

            <Section title="Children">
              <P>
                Speakist is not directed to children under 13. We do not
                knowingly collect information from children under 13. If
                you believe a child has signed up, please contact us and
                we will delete the account.
              </P>
              <P>
                In jurisdictions where the digital consent age is higher
                (e.g., 16 in parts of the EU under GDPR), we apply that
                local age threshold.
              </P>
            </Section>

            <Section title="International data transfers">
              <P>
                Speakist is operated from the United States. By using the
                service, you consent to your information being processed
                in the United States, where data protection laws may
                differ from those of your country.
              </P>
            </Section>

            <Section title="Changes to this policy">
              <P>
                We may update this policy from time to time. If we make
                material changes, we will notify you by email or in the
                dashboard. Continued use of the service after the effective
                date constitutes acceptance.
              </P>
            </Section>

            <Section title="Contact">
              <P>
                Questions or requests? Email{" "}
                <a
                  href="mailto:hello@brevoortstudio.com"
                  className="text-peach-deep hover:underline underline-offset-4"
                >
                  hello@brevoortstudio.com
                </a>
                .
              </P>
              <P className="text-muted-foreground">
                Brevoort Studio LLC
                <br />
                Colorado, USA
              </P>
            </Section>
          </div>
        </article>
      </main>
      <Footer />
    </div>
  );
}

// --- prose helpers ---------------------------------------------------------

function Section({
  title,
  children,
}: {
  title?: string;
  children: React.ReactNode;
}) {
  return (
    <section className="space-y-4">
      {title && (
        <h2 className="text-2xl font-semibold tracking-tight pt-4">
          {title}
        </h2>
      )}
      {children}
    </section>
  );
}

function P({
  children,
  className,
}: {
  children: React.ReactNode;
  className?: string;
}) {
  return <p className={className}>{children}</p>;
}

function UL({ children }: { children: React.ReactNode }) {
  return (
    <ul className="list-disc pl-6 space-y-2 marker:text-peach-deep/60">
      {children}
    </ul>
  );
}

function LI({ children }: { children: React.ReactNode }) {
  return <li>{children}</li>;
}
