// Custom Worker entrypoint.
//
// OpenNext generates `.open-next/worker.js` as the Next.js request handler.
// Next route handlers can't perform a WebSocket upgrade (they can't return a
// 101 response with a `webSocket`), so we wrap the generated worker: the one
// streaming route is intercepted here and everything else is delegated to
// Next unchanged.
//
// `wrangler.toml` points `main` at this file. The `.open-next/worker.js`
// import is resolved by wrangler at build time (it doesn't exist until
// `opennextjs-cloudflare build` has run), so this file is excluded from
// `tsc` typecheck — see tsconfig.json.

// @ts-expect-error resolved by wrangler build (generated by OpenNext)
import openNextWorker, {
  // @ts-expect-error resolved by wrangler build
  DOQueueHandler,
  // @ts-expect-error resolved by wrangler build
  DOShardedTagCache,
  // @ts-expect-error resolved by wrangler build
  BucketCachePurge,
} from "./.open-next/worker.js";
// OpenNext's request-context runner. It sets up the AsyncLocalStorage the
// package's getCloudflareContext()/getDb() read, so our streaming handler
// (which bypasses the Next request path) can still reach D1.
// @ts-expect-error resolved by wrangler build (generated by OpenNext)
import { runWithCloudflareRequestContext } from "./.open-next/cloudflare/init.js";
import { handleTranscribeStream } from "./src/lib/transcription/stream";

// Re-export the OpenNext Durable Object classes so their bindings keep
// resolving when this file is the entrypoint.
export { DOQueueHandler, DOShardedTagCache, BucketCachePurge };

export default {
  async fetch(request: Request, env: unknown, ctx: unknown): Promise<Response> {
    const url = new URL(request.url);
    const isWsUpgrade =
      (request.headers.get("Upgrade") ?? "").toLowerCase() === "websocket";

    if (url.pathname === "/api/transcribe/ws" && isWsUpgrade) {
      // Runs `fn` inside the OpenNext request context (ALS) so getDb()
      // resolves D1 — both for the initial handler and for the later
      // socket-close finalize callback.
      const runInContext = <T>(fn: () => Promise<T>): Promise<T> =>
        runWithCloudflareRequestContext(request, env, ctx, fn) as Promise<T>;
      return runInContext(() =>
        handleTranscribeStream(
          request,
          env as Parameters<typeof handleTranscribeStream>[1],
          ctx as Parameters<typeof handleTranscribeStream>[2],
          runInContext
        )
      );
    }

    return (
      openNextWorker as {
        fetch(request: Request, env: unknown, ctx: unknown): Promise<Response>;
      }
    ).fetch(request, env, ctx);
  },
};
